#!/usr/bin/bash

set -xe

yes_test=" -DBUILD_TESTS=ON"
no_test=" -DBUILD_TESTS=OFF"
debug=" -DBUILD_DEBUG=ON"
release=" -DBUILD_DEBUG=OFF"
flags=" -j4"

cmake="cmake . $debug $no_test '-b' build"
build="cmake --build build"
run="./build/Slug"

$cmake
$build

if [[ $1 == "run" ]]; then
	$run
elif [[ $1 == "layout-test" ]]; then
	./build/LayoutTest
fi
